Release v3.1.0
Chexxo/Server pull request #46
Opened 2021-05-17 11:34 UTC by SimonKindhauser

- [x] Refactor AWS Entry Point
- [x] Update Dependencies
- [x] Update Node to LTS 14

2021-05-17 12:14 UTC, SimonKindhauser commented
Update Node JS version in set-up documentation

2021-05-17 12:27 UTC, Vec7or commented on package.json
> +  "version": "3.1.0",
Please also adjust the version in the OpenApiDoc

2021-05-17 12:35 UTC, Vec7or requested changes

2021-05-17 12:35 UTC, Vec7or commented on package.json
> +  "version": "3.1.0",
Please also adjust the version in the openApiDoc

2021-05-17 12:35 UTC, Vec7or commented on package.json
> +    "typescript": "^4.0.2",
Why a downgrade?

2021-05-17 12:35 UTC, Vec7or commented on src/api/AWSAPIProvider.test.ts
> -test("Unsupported endpoint", () => {
Please replace this tests with new ones compatible with the new event.

2021-05-17 12:35 UTC, Vec7or commented on README.md
>  16. Make sure your function name is inside the `Lambda function` field and on `Save`. It is important, that you click on `Save` even if the function name was already correct.
This does no longer work or does it?

2021-05-17 12:37 UTC, SimonKindhauser commented on package.json
> +    "typescript": "^4.0.2",
version conflict, with typedoc

2021-05-17 12:40 UTC, SimonKindhauser commented on src/api/AWSAPIProvider.test.ts
> -test("Unsupported endpoint", () => {
there are no replacements since this functionality is now handled by aws.

2021-05-17 12:47 UTC, SimonKindhauser commented on README.md
>  16. Make sure your function name is inside the `Lambda function` field and on `Save`. It is important, that you click on `Save` even if the function name was already correct.
The button is gone, but I don't know what the purpose was.. should I just delete the related lines?

2021-05-17 19:23 UTC, Vec7or commented on README.md
>  16. Make sure your function name is inside the `Lambda function` field and on `Save`. It is important, that you click on `Save` even if the function name was already correct.
If it is no longer necessary you may delete the corresponding lines.

2021-05-19 09:12 UTC, Vec7or requested changes

2021-05-19 09:12 UTC, Vec7or commented on README.md
> +16. Make sure your function name is inside the `Lambda function` field.
Wrong number

2021-05-19 09:18 UTC, Vec7or approved these changes

2021-05-19 09:26 UTC, merged